kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crab
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: crab
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crab
  namespace: kube-system